obs space:
  name: insitu_profile_tesac_salinity
  obsdatain:
    engine:
      type: H5File
      obsfile: ${DATA}/obs/${OPREFIX}insitu_profile_tesac.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DATA}/diags/insitu_profile_tesac_salinity.${PDY}${cyc}.nc4
  simulated variables: [salinity]
  observed variables: [salinity]
  io pool:
    max pool size: 1
obs operator:
  name: VertInterp
  observation alias file: ./obsop_name_map.yaml
  vertical coordinate: sea_water_depth
  observation vertical coordinate: depth
  interpolation method: linear
obs error:
  covariance model: diagonal
obs filters:
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables:
        - ObsError/salinity
        coefs:
        - 1000.0
