obs space:
  name: insitu_surface_trkob_salinity
  obsdatain:
    engine:
      type: H5File
      obsfile: ${DATA}/obs/${OPREFIX}insitu_surface_trkob.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: ${DATA}/diags/insitu_surface_trkob_salinity.${PDY}${cyc}.nc4
  simulated variables: [seaSurfaceSalinity]
get values:
  time interpolation: linear
obs operator:
  name: Identity
  observation alias file: ./obsop_name_map.yaml
obs error:
  covariance model: diagonal
obs filters:
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables:
        - ObsError/seaSurfaceSalinity
        coefs:
        - 1000.0
