obs space:
  name: insitu_profile_mbuoy
  obsdatain:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/obs/${OPREFIX}insitu_profile_mbuoy.${PDY}${cyc}.nc4
  obsdataout:
    engine:
      type: H5File
      obsfile: !ENV ${DATA}/diags/insitu_profile_mbuoy.${PDY}${cyc}.nc4
  simulated variables: [waterTemperature]
  observed variables: [waterTemperature]
  io pool:
    max pool size: 1
obs operator:
  name: Composite
  components:
  - name: InsituTemperature
    variables:
    - name: waterTemperature
obs error:
  covariance model: diagonal
obs filters:
- filter: Perform Action
  action:
    name: assign error
    error function:
      name: ObsFunction/LinearCombination
      options:
        variables:
        - ObsError/waterTemperature
        coefs:
        - 1000.0
