obs space:
  name: sst_noaa19_l3u
  obsdatain:
    obsfile: ./obs/sst_noaa19_l3u.nc4
  obsdataout:
    obsfile: ./obs_out/sst_noaa19_l3u.$(OBS_DATE).nc4
  simulated variables: [sea_surface_temperature]
obs operator:
  name: Identity
obs error:
  covariance model: diagonal